name: Build Tor (aarch64) with Docker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Pull crossbuild Docker image
        run: docker pull multiarch/crossbuild

      - name: Build Tor inside Docker (aarch64)
        run: |
          docker run --rm -v ${{ github.workspace }}:/src \
            -w /src \
            multiarch/crossbuild \
            bash -c "
              apt update && \
              DEBIAN_FRONTEND=noninteractive apt install -y \
                autoconf automake libtool pkg-config libevent-dev && \
              ./autogen.sh && \
              ./configure \
                --host=aarch64-linux-gnu \
                --disable-asciidoc \
                --disable-manpage \
                --prefix=/src/tor-aarch64 && \
              make -j$(nproc) && \
              make install
            "

      - name: Upload compiled artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tor-aarch64
          path: tor-aarch64/
