- name: Build Tor inside Docker (aarch64)
  run: |
    docker run --rm -v ${{ github.workspace }}:/src \
      -w /src \
      multiarch/crossbuild \
      bash -c "
        dpkg --add-architecture arm64 && \
        sed -i 's|stretch|bullseye|g' /etc/apt/sources.list && \
        sed -i '/security.debian.org/d' /etc/apt/sources.list && \
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys \
          0E98404D386FA1D9 \
          6ED0E7B82643E131 \
          605C66F00D6C9793 && \
        apt-get update && \
        apt-get install -y \
          autoconf automake libtool pkg-config \
          libevent-dev:arm64 && \
        ./autogen.sh && \
        ./configure \
          --host=aarch64-linux-gnu \
          --disable-asciidoc \
          --disable-manpage \
          --prefix=/src/tor-aarch64 \
          --with-libevent-dir=/usr/lib/aarch64-linux-gnu && \
        make -j$(nproc) && \
        make install
      "
