name: Build Tor (aarch64) with Docker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Pull crossbuild Docker image
        run: docker pull multiarch/crossbuild

      - name: Build Tor inside Docker (aarch64)
        run: |
          docker run --rm -v ${{ github.workspace }}:/src \
            -w /src \
            multiarch/crossbuild \
            bash -c "
              # Update APT sources to use Debian Bullseye
              sed -i 's|http://deb.debian.org/debian stretch|http://deb.debian.org/debian bullseye|g' /etc/apt/sources.list && \
              
              # Import missing GPG keys
              apt-key adv --keyserver keyserver.ubuntu.com --recv-keys \
                0E98404D386FA1D9 \
                6ED0E7B82643E131 \
                605C66F00D6C9793 && \
                
              # Update package list and install dependencies
              apt update && \
              DEBIAN_FRONTEND=noninteractive apt install -y \
                autoconf automake libtool pkg-config libevent-dev && \
              
              # Build Tor
              ./autogen.sh && \
              ./configure \
                --host=aarch64-linux-gnu \
                --disable-asciidoc \
                --disable-manpage \
                --prefix=/src/tor-aarch64 && \
              make -j$(nproc) && \
              make install
            "

      - name: Upload compiled artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tor-aarch64
          path: tor-aarch64/
