name: Build Tor for AARCH64

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Tor inside Docker (aarch64)
        run: |
          docker run --rm -v ${{ github.workspace }}:/src \
            -w /src \
            multiarch/crossbuild \
            bash -c '
              set -e

              apt-get update
              DEBIAN_FRONTEND=noninteractive apt-get install -y \
                autoconf \
                automake \
                libtool \
                pkg-config \
                crossbuild-essential-arm64 \
                libevent-dev

              export CC=aarch64-linux-gnu-gcc
              export LD=aarch64-linux-gnu-ld
              export AR=aarch64-linux-gnu-ar
              export RANLIB=aarch64-linux-gnu-ranlib
              export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig

              ./autogen.sh

              ./configure \
                --host=aarch64-linux-gnu \
                --disable-asciidoc \
                --disable-manpage \
                --prefix=/src/tor-aarch64

              make -j$(nproc)
              make install
            '
