name: Build Tor aarch64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:bookworm

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            libevent-dev \
            libssl-dev \
            zlib1g-dev \
            autoconf \
            automake \
            libtool \
            pkg-config \
            ca-certificates \
            git

      - name: Clone and Build Tor
        run: |
          git clone https://git.torproject.org/tor.git
          cd tor
          ./autogen.sh
          ./configure
          make -j$(nproc)
          make install DESTDIR=/tmp/tor-aarch64

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tor-aarch64
          path: /tmp/tor-aarch64
